language: node_js
node_js:
  - 12
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - npm install -g codecov
script:
  - echo "//registry.npmjs.org/:_authToken=${NPM_RO_TOKEN}" > .npmrc
  - CI=true yarn test --coverage
  - codecov
